package com.nexus.integration.notification;

public enum NotificationEvent {
    TASK_COMPLETED,
    MINDBANK_INGESTED,
    SUBSCRIPTION_EXPIRING,
    SUBSCRIPTION_LOW_BALANCE,
    API_KEY_PLAN_EXPIRING,
    API_KEY_LOW_BALANCE,
    CREDENTIAL_EXPIRING,
    CODING_PRACTICE_NOTE_GENERATED,
    CRAWL_COMPLETED,
    TODO_REMINDER
}
